CREATE EXTENSION IF NOT EXISTS postgis;


CREATE TABLE polska (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    geom geometry(MultiPolygon,2180) NULL,
    gml_id character varying(254) NULL,
    jpt_sjr_ko character varying(254) NULL,
    jpt_powier character varying(254) NULL,
    jpt_kod_je character varying(254) NULL,
    jpt_nazwa_ character varying(254) NULL,
    jpt_organ_ character varying(254) NULL,
    jpt_jor_id character varying(254) NULL,
    wersja_od character varying(254) NULL,
    wersja_do character varying(254) NULL,
    wazny_od character varying(254) NULL,
    wazny_do character varying(254) NULL,
    jpt_kod__1 character varying(254) NULL,
    jpt_nazwa1 character varying(254) NULL,
    jpt_organ1 character varying(254) NULL,
    jpt_wazna_ character varying(254) NULL,
    id_bufora_ character varying(254) NULL,
    id_bufora1 character varying(254) NULL,
    id_technic character varying(254) NULL,
    iip_przest character varying(254) NULL,
    iip_identy character varying(254) NULL,
    iip_wersja character varying(254) NULL,
    jpt_kj_iip character varying(254) NULL,
    jpt_kj_i_1 character varying(254) NULL,
    jpt_kj_i_2 character varying(254) NULL,
    jpt_opis character varying(254) NULL,
    jpt_sps_ko character varying(254) NULL,
    id_bufor_1 character varying(254) NULL,
    jpt_id character varying(254) NULL,
    jpt_powi_1 character varying(254) NULL,
    jpt_kj_i_3 character varying(254) NULL,
    jpt_geomet character varying(254) NULL,
    jpt_geom_1 character varying(254) NULL,
    shape_leng character varying(254) NULL,
    shape_area character varying(254) NULL,
    rodzaj character varying(254) NULL,
    CONSTRAINT polska_pkey PRIMARY KEY (id)
);


CREATE TABLE wojewodztwa (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    geom geometry(MultiPolygon,2180) NULL,
    gml_id character varying(254) NULL,
    jpt_sjr_ko character varying(254) NULL,
    jpt_powier character varying(254) NULL,
    jpt_kod_je character varying(254) NULL,
    jpt_nazwa_ character varying(254) NULL,
    jpt_organ_ character varying(254) NULL,
    jpt_jor_id character varying(254) NULL,
    wersja_od character varying(254) NULL,
    wersja_do character varying(254) NULL,
    wazny_od character varying(254) NULL,
    wazny_do character varying(254) NULL,
    jpt_kod__1 character varying(254) NULL,
    jpt_nazwa1 character varying(254) NULL,
    jpt_organ1 character varying(254) NULL,
    jpt_wazna_ character varying(254) NULL,
    id_bufora_ character varying(254) NULL,
    id_bufora1 character varying(254) NULL,
    id_technic character varying(254) NULL,
    iip_przest character varying(254) NULL,
    iip_identy character varying(254) NULL,
    iip_wersja character varying(254) NULL,
    jpt_kj_iip character varying(254) NULL,
    jpt_kj_i_1 character varying(254) NULL,
    jpt_kj_i_2 character varying(254) NULL,
    jpt_opis character varying(254) NULL,
    jpt_sps_ko character varying(254) NULL,
    id_bufor_1 character varying(254) NULL,
    jpt_id character varying(254) NULL,
    jpt_powi_1 character varying(254) NULL,
    jpt_kj_i_3 character varying(254) NULL,
    jpt_geomet character varying(254) NULL,
    jpt_geom_1 character varying(254) NULL,
    shape_leng character varying(254) NULL,
    shape_area character varying(254) NULL,
    regon character varying(254) NULL,
    rodzaj character varying(254) NULL,
    CONSTRAINT wojewodztwa_pkey PRIMARY KEY (id)
);


CREATE TABLE points (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    location geometry NOT NULL,
    voivodeship_id integer NULL,
    CONSTRAINT pk_points PRIMARY KEY (id),
    CONSTRAINT fk_points_voivodeships_voivodeship_id FOREIGN KEY (voivodeship_id) REFERENCES wojewodztwa (id)
);


CREATE INDEX ix_points_voivodeship_id ON points (voivodeship_id);


