// <auto-generated />
using Geo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Geo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221231095316_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Geo.Models.Polska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<MultiPolygon>("Geom")
                        .HasColumnType("geometry(MultiPolygon,2180)")
                        .HasColumnName("geom");

                    b.Property<string>("GmlId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("gml_id");

                    b.Property<string>("IdBufor1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("id_bufor_1");

                    b.Property<string>("IdBufora")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("id_bufora_");

                    b.Property<string>("IdBufora1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("id_bufora1");

                    b.Property<string>("IdTechnic")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("id_technic");

                    b.Property<string>("IipIdenty")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("iip_identy");

                    b.Property<string>("IipPrzest")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("iip_przest");

                    b.Property<string>("IipWersja")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("iip_wersja");

                    b.Property<string>("JptGeom1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_geom_1");

                    b.Property<string>("JptGeomet")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_geomet");

                    b.Property<string>("JptId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_id");

                    b.Property<string>("JptJorId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_jor_id");

                    b.Property<string>("JptKjI1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kj_i_1");

                    b.Property<string>("JptKjI2")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kj_i_2");

                    b.Property<string>("JptKjI3")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kj_i_3");

                    b.Property<string>("JptKjIip")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kj_iip");

                    b.Property<string>("JptKod1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kod__1");

                    b.Property<string>("JptKodJe")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kod_je");

                    b.Property<string>("JptNazwa")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_nazwa_");

                    b.Property<string>("JptNazwa1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_nazwa1");

                    b.Property<string>("JptOpis")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_opis");

                    b.Property<string>("JptOrgan")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_organ_");

                    b.Property<string>("JptOrgan1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_organ1");

                    b.Property<string>("JptPowi1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_powi_1");

                    b.Property<string>("JptPowier")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_powier");

                    b.Property<string>("JptSjrKo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_sjr_ko");

                    b.Property<string>("JptSpsKo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_sps_ko");

                    b.Property<string>("JptWazna")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_wazna_");

                    b.Property<string>("Rodzaj")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("rodzaj");

                    b.Property<string>("ShapeArea")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("shape_area");

                    b.Property<string>("ShapeLeng")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("shape_leng");

                    b.Property<string>("WaznyDo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("wazny_do");

                    b.Property<string>("WaznyOd")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("wazny_od");

                    b.Property<string>("WersjaDo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("wersja_do");

                    b.Property<string>("WersjaOd")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("wersja_od");

                    b.HasKey("Id")
                        .HasName("polska_pkey");

                    b.ToTable("polska", (string)null);
                });

            modelBuilder.Entity("Geo.Models.Wojewodztwa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<MultiPolygon>("Geom")
                        .HasColumnType("geometry(MultiPolygon,2180)")
                        .HasColumnName("geom");

                    b.Property<string>("GmlId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("gml_id");

                    b.Property<string>("IdBufor1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("id_bufor_1");

                    b.Property<string>("IdBufora")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("id_bufora_");

                    b.Property<string>("IdBufora1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("id_bufora1");

                    b.Property<string>("IdTechnic")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("id_technic");

                    b.Property<string>("IipIdenty")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("iip_identy");

                    b.Property<string>("IipPrzest")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("iip_przest");

                    b.Property<string>("IipWersja")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("iip_wersja");

                    b.Property<string>("JptGeom1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_geom_1");

                    b.Property<string>("JptGeomet")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_geomet");

                    b.Property<string>("JptId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_id");

                    b.Property<string>("JptJorId")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_jor_id");

                    b.Property<string>("JptKjI1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kj_i_1");

                    b.Property<string>("JptKjI2")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kj_i_2");

                    b.Property<string>("JptKjI3")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kj_i_3");

                    b.Property<string>("JptKjIip")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kj_iip");

                    b.Property<string>("JptKod1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kod__1");

                    b.Property<string>("JptKodJe")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_kod_je");

                    b.Property<string>("JptNazwa")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_nazwa_");

                    b.Property<string>("JptNazwa1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_nazwa1");

                    b.Property<string>("JptOpis")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_opis");

                    b.Property<string>("JptOrgan")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_organ_");

                    b.Property<string>("JptOrgan1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_organ1");

                    b.Property<string>("JptPowi1")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_powi_1");

                    b.Property<string>("JptPowier")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_powier");

                    b.Property<string>("JptSjrKo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_sjr_ko");

                    b.Property<string>("JptSpsKo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_sps_ko");

                    b.Property<string>("JptWazna")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("jpt_wazna_");

                    b.Property<string>("Regon")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("regon");

                    b.Property<string>("Rodzaj")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("rodzaj");

                    b.Property<string>("ShapeArea")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("shape_area");

                    b.Property<string>("ShapeLeng")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("shape_leng");

                    b.Property<string>("WaznyDo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("wazny_do");

                    b.Property<string>("WaznyOd")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("wazny_od");

                    b.Property<string>("WersjaDo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("wersja_do");

                    b.Property<string>("WersjaOd")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("wersja_od");

                    b.HasKey("Id")
                        .HasName("wojewodztwa_pkey");

                    b.ToTable("wojewodztwa", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
